CREATE TABLE OTP_TRACKING (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MOBILE_NUMBER BIGINT NOT NULL,
    SESSION_ID VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME ,
    EXPIRATION_TIME DATETIME,   
    FAILED_ATTEMPTS INT DEFAULT 0,
    IS_VERIFIED TINYINT DEFAULT 0,
    STATUS TINYINT DEFAULT 1
);
