CREATE TABLE USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(80) UNIQUE NOT NULL,
    MOBILE_NUMBER INT UNIQUE NOT NULL,
    IS_MOBILE_VERIFIED BOOLEAN DEFAULT FALSE,
    AGREED_TO_TERMS BOOLEAN DEFAULT FALSE,
    CREATED_AT DATETIME 
);
